parameters:
#    smart_project_sync.example.class: SmartProject\SyncBundle\Example

services:
#    smart_project_sync.example:
#        class: %smart_project_sync.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
