parameters:
    smart_project_sync.providers.factory.class: SmartProject\SyncBundle\Providers\Factory

services:
    smart_project_sync.providers.factory:
        class: %smart_project_sync.providers.factory.class%
        arguments: [%smart_project_sync.providers%, %smart_project_sync.clients%]
        calls:
            - [ setContainer, [@service_container] ]

