#smart_project_sync:
#    resource: "@SmartProjectSyncBundle/Resources/config/routing.yml"
#    type:     annotation
#    prefix:   /sync

smart_project_timesheet:
    resource: "@SmartProjectTimesheetBundle/Controller"
    type:     annotation
    prefix:   /timesheet

smart_project_front:
    resource: "@SmartProjectFrontBundle/Controller"
    type:     annotation
    prefix:   /

smart_project_security:
    resource: "@SmartProjectSecurityBundle/Controller"
    type:     annotation
    prefix:   /

smart_project_project:
    resource: "@SmartProjectProjectBundle/Controller"
    type:     annotation
    prefix:   /

#login + logout
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
