<?php

namespace SmartProject\SyncBundle\Entity\Provider;

use Doctrine\ORM\EntityRepository;

/**
 * ProviderRedmineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRedmineRepository extends EntityRepository
{
}
