<?php

namespace SmartProject\TimesheetBundle\Entity\Task;

use Doctrine\ORM\EntityRepository;

/**
 * TaskCalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskCalendarRepository extends EntityRepository
{
}
