parameters:
    smart_project_project.redmine.class: SmartProject\ProjectBundle\Provider\RedmineProvider

services:
    smart_project_project.redmine:
        class: %smart_project_project.redmine.class%
        arguments: [@doctrine, %redmine%]
