parameters:
    smart_project_project.synchronize.class: SmartProject\ProjectBundle\Services\Synchronize

services:
    smart_project_project.synchronize:
        class: %smart_project_project.synchronize.class%
        arguments: [@doctrine.orm.entity_manager]
