<?php

namespace SmartProject\TimesheetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimesheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimesheetRepository extends EntityRepository
{
}
