parameters:
    smart_project_front.menu_builder.class:       SmartProject\FrontBundle\Menu\MenuBuilder
    smart_project_front.menu.voter.request.class: SmartProject\FrontBundle\Menu\Voter\RequestVoter

services:
    smart_project_front.menu_builder:
        class: %smart_project_front.menu_builder.class%
        arguments: ["@knp_menu.factory"]

    smart_project_front.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: smart_project_front.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    smart_project_front.menu.user:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: smart_project_front.menu_builder
        factory_method: createUserMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: user } # The alias is what is used to retrieve the menu

    smart_project_front.menu.voter.request:
        class: %smart_project_front.menu.voter.request.class%
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }

