parameters:
#    smart_project_front.example.class: SmartProject\FrontBundle\Example

services:
#    smart_project_front.example:
#        class: %smart_project_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
