parameters:
#    smart_project_front.example.class: SmartProject\FrontBundle\Example

services:
#    smart_project_front.example:
#        class: %smart_project_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    smart_project_front.menu_builder:
        class: SmartProject\FrontBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    smart_project_front.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: smart_project_front.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

