parameters:
    smart_project_timesheet.type.timesheet_task.class: SmartProject\TimesheetBundle\Form\TimesheetTaskType

services:
    smart_project_timesheet.type.timesheet_task:
        class: %smart_project_timesheet.type.timesheet_task.class%
        tags:
            - { name: form.type, alias: smartproject_collection_task }