<?php

namespace SmartProject\ProjectBundle\Entity;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * BaseProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseProjectRepository extends NestedTreeRepository
{

}
