<?php

namespace SmartProject\ProjectBundle\Entity;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends BaseProjectRepository
{
    /**
     * Finds entities by a set of criteria.
     *
     * @param array $criteria
     * @param array|null $orderBy
     * @param int|null $limit
     * @param int|null $offset
     * @return array The objects.
     */
    public function findWithProjectsBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
//        $this->getRootNodesQueryBuilder()
        return array();
    }

    /**
     * @see getChildrenQueryBuilder
     */
    public function childrenQueryBuilder($node = null, $direct = false, $sortByField = null, $direction = 'ASC', $includeNode = false)
    {
        $queryBuilder = parent::childrenQueryBuilder($node, $direct, $sortByField, $direction, $includeNode);

        $queryBuilder->andWhere('node INSTANCE OF SmartProject\ProjectBundle\Entity\Client')
          ->orderBy('node.root', 'asc')
          ->addOrderBy('node.lft', 'asc');

        return $queryBuilder;
    }
}
