<?php

namespace SmartProject\ProjectBundle\Entity;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends BaseProjectRepository
{
    /**
     * @see getChildrenQueryBuilder
     */
    public function childrenQueryBuilder($node = null, $direct = false, $sortByField = null, $direction = 'ASC', $includeNode = false)
    {
        $queryBuilder = parent::childrenQueryBuilder($node, $direct, $sortByField, $direction, $includeNode);

        $queryBuilder->andWhere('node INSTANCE OF SmartProject\ProjectBundle\Entity\Contract')
          ->orderBy('node.root', 'asc')
          ->addOrderBy('node.lft', 'asc');

        return $queryBuilder;
    }
}
