<?php

namespace SmartProject\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    /**
     * Finds all entities in the repository.
     *
     * @return array The entities.
     */
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder()
          ->select('p, r')
          ->from($this->_entityName, 'p')
          ->leftJoin('p.redmineProject', 'r');

        return $query->getQuery()->execute();
    }
}
